README.md
package.json
src/amo-client.js
src/index.js
tests/test.amo-client.js
tests/test.sign.js

Fixes https://github.com/mozilla/sign-addon/issues/16

Allow configuration of the download directory

---

src/amo-client.js

Fixes https://github.com/mozilla/sign-addon/issues/43

fix: Added missing new line after download progress bar

---

tests/test.amo-client.js

Fixes https://github.com/mozilla/sign-addon/issues/42

fix: Fixed a flaky test that relied on timestamps

---

README.md
src/amo-client.js
src/index.js
tests/test.amo-client.js
tests/test.sign.js

Fixes https://github.com/mozilla/sign-addon/issues/49

feat: Added `apiProxy` to specify a proxy server

---

.travis.yml
src/index.js

I think this will fix https://github.com/mozilla-jetpack/jpm/pull/552 -- thanks to @rpl for help debugging!

fix: Fixes `Cannot find module 'any-promise'` on npm 2.x

---

src/amo-client.js
tests/test.amo-client.js

Fixes https://github.com/mozilla/sign-addon/issues/134

fix: API errors are displayed even if the status code is incorrect

---

src/amo-client.js
tests/test.amo-client.js

Fixes https://github.com/mozilla/sign-addon/issues/74

fix: Fixed error handling when download response is a 404

---

src/amo-client.js
tests/test.amo-client.js

Fixes https://github.com/mozilla/sign-addon/issues/321

Fix request() call

---

.travis.yml
README.md
package-lock.json
package.json
src/@types/deepcopy/index.d.ts
src/amo-client.js
src/index.js
tsconfig.json

fixes https://github.com/mozilla/sign-addon/issues/326

feat: Add static types via TypeScript + JSDoc

---

src/amo-client.js

Fixes https://github.com/mozilla/sign-addon/issues/319

Increase signedStatusCheckTimeout

---

.travis.yml
README.md
package-lock.json
package.json

Setup codecov

---

.travis.yml

Fixes https://github.com/mozilla/sign-addon/issues/447

Update travis config to new dpl2 format

---

src/index.js

I noticed a typo in this file.

change milleseconds to milliseconds.

---

README.md

change milleseconds to milliseconds

---

.travis.yml

Minor update of the Travis-CI config to be in sync with what we have elsewhere.

Update travis-ci config

---

src/amo-client.js
src/index.js
tests/amo-client.spec.js
tests/index.spec.js

Fixes #710 
@willdurand _A please review

Made progress bar optional in Client

---

src/index.js

This fixes a recent TypeScript change.

chore(deps): add type to error

---

src/amo-client.js
tests/amo-client.spec.js

Fixes #880
---
It's longer than before but a bit more explicit and useful. I removed the last status, which didn't seem very useful to me.

feat(): Update message when signing took too long to complete

---

.circleci/config.yml

ci: update circleci images to cimg

---

.circleci/config.yml
tests/functional/imports.spec.js

ci: switch to testing on node 14 and 16
