README.md
Switch the import to require as that what node/javascript uses.
=> Change the example code to use standard node syntax for requiring sign-addon

package.json
The webpack banner triggers an import of this on the first line of the distribution.
=> fix(): Added missing source-map-support dependency

README.md, src/amo-client.js, src/index.js, tests/test.amo-client.js, tests/test.sign.js
This is required for https://github.com/mozilla/web-ext/issues/178
=> feat: You can now sign web extensions without IDs

src/amo-client.js, src/index.js, tests/test.amo-client.js, tests/test.sign.js
The maximum allowed expiration time for JWT authentication has been increased in https://github.com/mozilla/addons-server/pull/3686 to address a problem where slow file uploads delay the validation of the expiration. This bumps the default expiration in the client and also lets the caller configure the value (if needed).
=> fix: Fixed timeouts in case of slow XPI uploads to the signing server

package.json
I think I fix the bug that make npm fail, and I add keyword "Add-on" into package.json file as well.
=> chore: Add keywords to package.json

package.json
This avoids the following deprecation warning upon `npm install`:
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
`request` switched from `node-uuid` to `uuid` in version 2.79.0:
https://github.com/request/request/commit/263e16ec89edb8041657edb9280d9b0039146845
=> chore(package): update request to version 2.79.0

README.md, src/amo-client.js, src/index.js, tests/test.amo-client.js, tests/test.sign.js
Fixes #248
I'm not sure where I should add unit tests if any, would appreciate pointers and I can update this PR. I have tested the changes using my addon: I can specify unlisted channel when the previously used channel was listed and the result is unlisted ready for self-hosting.
=> feat: Added optional `channel` parameter

package.json
This patch release was a precaution against a previously released malicious version https://github.com/conventional-changelog/conventional-changelog/issues/282#issuecomment-365367804
=> chore: update conventional-changelog-cli to version 1.3.13

.travis.yml, package.json
This PR updates jsonwebtoken and request to their last versions, which is needed to solve the following security issue with their dependencies, e.g.:
- request@2.87.0, which updates to a non vulnerable version:
- hoek (https://nodesecurity.io/advisories/566)
- tunnel-agent (https://nodesecurity.io/advisories/598)
- jsonwebtoken@8.2.1, which updates to a non vulnerable version:
- hoek (https://nodesecurity.io/advisories/566)
The travis config is also being updated to run the tests on nodejs 6 and nodejs 8.
=> fix: Update direct npm production deps

.travis.yml, README.md, package.json, src/amo-client.js, tests/test.amo-client.js
Fixes #269
I updated README, node versions for travis and version in package.json
The test failing in v10 is because `JSON.stringify` isn't failing to convert `process` (and assume other  complex object too).
I'm tempt to remove the test, but what do you think?
https://github.com/mozilla/sign-addon/blob/3473ccdb8cf5f9de8554cd86186c49af21357d62/tests/test.amo-client.js#L971-L974
https://github.com/mozilla/sign-addon/blob/3473ccdb8cf5f9de8554cd86186c49af21357d62/src/amo-client.js#L670-L688
=> drop support for node 6

.babelrc, .travis.yml, package-lock.json, package.json, src/PseudoProgress.js, src/amo-client.js, src/index.js, tests/PseudoProgress.spec.js, tests/test.amo-client.js
This patch has been extracted while working on https://github.com/mozilla/sign-addon/pull/323. That will likely reduce the diff of this other patch and hopefully make it easier to follow.
Likely fixes https://github.com/mozilla/sign-addon/issues/324
Changes:
- drop node 8 support (may not be needed but...)
- `web-ext` removed Node 8 support in https://github.com/mozilla/web-ext/issues/1556
- move `PseudoProgress` class to its own file
- switch to async/await when easily possible
=> feat: drop node 8 support, start adding async/await

tests/helpers.js, tests/test.amo-client.js
This patch adds a parent `describe()` block in a test file and move two mock classes into a new file (cleanup). The diff is much smaller with `?w=1` in the URL 😉
=> refactor: Move mock classes to tests/helpers.js

package.json, tsconfig.json
The `noEmit` value should be defined in tsconfig so that IDEs such as VSCode know what to do.
As you might have guessed, I've been trying to go all in on VSCode lately 😬
=> Move noEmit into tsconfig

src/PseudoProgress.js, src/amo-client.js, src/index.js, tests/helpers.js, tests/test.amo-client.js, tests/test.sign.js
Fixes #320
---
This allows to give the developer more information about what's going on behind
the scenes with the signing process.
New output looks like this:
```
node test.js
Validating add-on [........................................................................................................................................................................]
Validation results: http://olympia.test/en-US/developers/upload/46f4e2470a1b47ef9582783d3a5f76b0
Signing add-on [...........................................................................................................................................................................]
Downloading signed files: 100%
Downloaded:
./addon_submitted_with_sign_addon-2.0.0-an+fx.xpi
The following signed files were downloaded:
[ …
```
=> refactor: wait for validation & signing separately

README.md, src/amo-client.js, tests/amo-client.spec.js
When using sign-addon programatically, having more details on the response object would be nice.
=> feat: Provide more detailed errors in the response object

.gitignore, .npmignore, package.json
While looking to the diff on the last released version, I noticed that we are currently including in the sign-addon package released on npm the generated coverage files.
(To be fair there are also other files that we may exclude from the npm package, see https://unpkg.com/browse/sign-addon@2.0.3/)
=> fix: Added coverage dir to .npmignore

package-lock.json, package.json, webpack.config.js
This would have been the proper fix to #383 .
For more details, see https://github.com/mozilla/web-ext/pull/1814 and the linked PRs.
=> fix: Use webpack-node-externals to avoid bundling node_modules

.prettierignore, .travis.yml, README.md, package-lock.json, package.json, src/index.js, tests/fixtures/import-as-esm/test-import.mjs, tests/fixtures/require-as-cjs/test-require.js, tests/functional/imports.spec.js, webpack.config.js
Fixes https://github.com/mozilla/sign-addon/issues/517
---
This will require a new major version as the default import has changed (and it might not work with web-ext, see below), but the API should be more consistent now. I also ported some "test-util" code from `web-ext`.
Patch for web-ext:
```diff
diff --git a/src/cmd/sign.js b/src/cmd/sign.js
index a011ea4..8472c73 100644
--- a/src/cmd/sign.js
+++ b/src/cmd/sign.js
@@ -2,7 +2,7 @@
import path from 'path';
import {fs} from 'mz';
-import defaultAddonSigner from 'sign-addon';
+import { signAddon as defaultAddonSigner } from 'sign-addon';
import defaultBuilder from './build';
import getValidatedManifest, {getManifestId} from '../util/manifest';
```
=> Expose a consistent API for both ESM and CJS

README.md
The default timeout for signing was updated a while back in commit 47d4cf23d6ae3d5f0961e6c461b28836111fa5c9, but the example in the README wasn't. This change just brings the README example back up to date with what's in the code.
=> docs: Aligned README example with code timeout default

.circleci/config.yml
Add-ons services already use Node 16 by default (or in production). Let's make it the default in the other repos too.
=> Use Node 16 and 18 in CI
